version: '3.8'

services:
  api:
    build:
      context: ./src/api
    networks:
      - api_network
      - frontend_network
    environment:
      - SERVICE_FQDN_DIRECTMONEROAPI_5000=/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./src/frontend
    networks:
      - frontend_network
    environment:
      - SERVICE_FQDN_DIRECTMONEROFRONTEND_3030
      - VUE_APP_API_ADDRESS=${SERVICE_FQDN_DIRECTMONEROAPI_5000}

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  postgres_data: