version: '3.8'

services:
  api:
    build:
      context: ./src/api
    environment:
      - SERVICE_FQDN_DIRECTMONEROAPI_5000
      - DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@database:5432/directmonero
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./src/frontend
    environment:
      - SERVICE_FQDN_DIRECTMONEROFRONTEND_3030
      - VUE_APP_API_ADDRESS=${SERVICE_FQDN_DIRECTMONEROAPI_5000}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
      POSTGRES_DB: directmonero
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVICE_USER_POSTGRES}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
