version: '3.8'

services:
  api:
    image: directmonero-api:latest
    environment:
      - JWT_SECRET=ienihwjeh9039h293ju32hj3h
      - DATABASE_URL=mongodb://database:27017/directmonero
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: directmonero-frontend:latest
    environment:
      - API_ADDRESS=http://localhost:5000
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3030:3030"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mongo:8
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
