services:
  api:
    build:
      context: ./src/api
    ports:
      - "5000:5000"
    networks:
      - api_network
      - frontend_network
    environment:
      - JWT_SECRET=secret
      - DATABASE_URL=mongodb://database:27017/directmonero
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/api/v1/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3030:3030"
    networks:
      - frontend_network
    environment:
      - API_ADDRESS=http://localhost:5000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  mongo_data: