services:
  api:
    build:
      context: ./src/api
    ports:
      - "5000:5000"
    networks:
      - api_network
      - frontend_network

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_network
    environment:
      - VUE_APP_API_ADDRESS=http://localhost:5000

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  postgres_data: