services:
  api:
    build:
      context: ./src/api
    ports:
      - "5000:5000"
    networks:
      - api_network
      - frontend_network
    environment:
      - JWT_SECRET=secret
      - DATABASE_URL=mongodb://database:27017/directmonero

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3030:3030"
    networks:
      - frontend_network
    environment:
      - VITE_APP_API_ADDRESS=http://localhost:5000

  database:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  mongo_data:
