version: '3.8'

services:
  api:
    build:
      context: ./src/api
    environment:
      - SERVICE_FQDN_DIRECTMONEROAPI_5000
      - DATABASE_URL=mongodb://${SERVICE_USER_MONGO}:${SERVICE_PASSWORD_MONGO}@database:27017/directmonero
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./src/frontend
    environment:
      - SERVICE_FQDN_DIRECTMONEROFRONTEND_3030
      - VUE_APP_API_ADDRESS=${SERVICE_FQDN_DIRECTMONEROAPI_5000}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SERVICE_USER_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_PASSWORD_MONGO}
      MONGO_INITDB_DATABASE: directmonero
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--username", "$$MONGO_INITDB_ROOT_USERNAME", "--password", "$$MONGO_INITDB_ROOT_PASSWORD", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  mongo_data:
